// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8se8Q3dHIMKJhAZN31EDLxg5tOMAgguE',
    appId: '1:291172556430:web:89249d13a34a339e7eb3df',
    messagingSenderId: '291172556430',
    projectId: 'todos-a616c',
    authDomain: 'todos-a616c.firebaseapp.com',
    storageBucket: 'todos-a616c.appspot.com',
    measurementId: 'G-1CJ9PES27X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFOniNVLQz0j8G0RNr8ZygUDq7WaRx-Go',
    appId: '1:291172556430:android:18e230f0dc79739f7eb3df',
    messagingSenderId: '291172556430',
    projectId: 'todos-a616c',
    storageBucket: 'todos-a616c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4bk6DdofurUbUONX6ftidm5SLZ0VuQbY',
    appId: '1:291172556430:ios:c09087bf472cd8267eb3df',
    messagingSenderId: '291172556430',
    projectId: 'todos-a616c',
    storageBucket: 'todos-a616c.appspot.com',
    iosBundleId: 'com.example.toDos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4bk6DdofurUbUONX6ftidm5SLZ0VuQbY',
    appId: '1:291172556430:ios:760fada2a6987fbc7eb3df',
    messagingSenderId: '291172556430',
    projectId: 'todos-a616c',
    storageBucket: 'todos-a616c.appspot.com',
    iosBundleId: 'com.example.toDos.RunnerTests',
  );
}
